FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8
WORKDIR /app
COPY ./backend /app
RUN pip install --no-cache-dir -r requirements.txt
CMD ["uvicorn", "fastapi_app:app", "--host", "0.0.0.0", "--port", "80"]
